### ISSUE TITLE
Getting array index out of bound exception while applying filter

### ISSUE THREAD

**Issue by Jarish** [dntks/easyLUT#1]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1048576; index=1118265
                                                                               at hu.don.easylut.lutimage.LUTImage.getPixelByIndex(LUTImage.java:63)
                                                                               at hu.don.easylut.lutimage.LUTImage.getColorPixelOnLut(LUTImage.java:59)
                                                                               at hu.don.easylut.filter.CreatingNewBitmap.applyLut(CreatingNewBitmap.java:21)
                                                                               at hu.don.easylut.filter.LUTFilter.apply(LUTFilter.java:24)

**Comment by dntks** [comment]
Could you post what LUT image you are using? I'll check it then.
