### ISSUE TITLE
Getting java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pateljc** [dntks/easyLUT#4]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1048576; index=1060561 at hu.don.easylut.lutimage.LUTImage.getPixelByIndex(LUTImage.java:63)  at hu.don.easylut.lutimage.LUTImage.getColorPixelOnLut(LUTImage.java:59) at hu.don.easylut.filter.CreatingNewBitmap.applyLut(CreatingNewBitmap.java:21) at hu.don.easylut.filter.LUTFilter.apply(LUTFilter.java:24)

/**********************/
i m using 512*512 square image 
/**********************/

**Comment by dntks** [comment]
Could you send me the image so I can test what could be the problem?

**Comment by pateljc** [comment]
![lut_img](https://user-images.githubusercontent.com/29919763/35135513-bc5e4178-fd03-11e7-9bf0-6cbe21309f64.png)

**Comment by pateljc** [comment]
Filter filter = EasyLUT.fromBitmap()
                    .withBitmap(helper.getBitmap_from_Drawable(R.drawable.aa_b)) 
                    .createFilter();
bmp = filter.apply(captured);
iv.setImageBitmap(bmp);

/**/
And here is my code
/**/

**Comment by dntks** [comment]
Did you put your lut bitmap (aa_b) into the drawable-nodpi folder?
For me your lut works.
I see that you create a Bitmap from a resource, have you considered using the library with resources, like this?
```
EasyLUT.fromResourceId()
       .withResources(resources)
       .withLutBitmapId(R.drawable.aa_b)
       .createFilter();
```

**Comment by pateljc** [comment]
its not working i have my lut in my drawable folder  
i tried your sample application as well  but it not showing any image 
i tried your application in multiple device bt it showing same result

**Comment by pateljc** [comment]
log said  processing bitmap failed

**Comment by dntks** [comment]
What device do you use? Can it be because of large bitmap loading?

**Comment by Sulfkain** [comment]
This happens to me too, but my filter is one-line filtered (supposed to be supported)![brightcontrast](https://user-images.githubusercontent.com/17082246/46945805-24633580-d076-11e8-8968-659b72a5624b.png).

I go to see the class `LutAlignment`, and there is only 2 classes (Hald and Square shape filter).
When I load my one-line filter, the lib create the filter as square, so seems the getX and getY methods returns something higher than the actual size of the array.

**Comment by dntks** [comment]
Hi Sulfkain,

Sorry for the late answer, I'll check soon what can cause the problem!

**Comment by NinhPhamHai** [comment]
hello dntks, are you working to fix that issues???
